owner: iddqd-uk
repo: status

assignees: [tarampampam] # To be assigned to every downtime issue

sites:
  - name: Index page
    url: https://iddqd.uk
    maxResponseTime: 5000
  - name: Holy shit blog
    url: https://blog.iddqd.uk
    maxResponseTime: 10000
  - name: Traefik UI
    url: https://traefik.iddqd.uk
    maxResponseTime: 10000
    expectedStatusCodes: [401]
  - name: Consul UI
    url: https://consul.iddqd.uk
    maxResponseTime: 10000
    expectedStatusCodes: [401]
  - name: Nomad UI
    url: https://nomad.iddqd.uk
    maxResponseTime: 10000
    expectedStatusCodes: [401]
  - name: Nomad API
    url: https://nomad.iddqd.uk/v1/status/leader
    maxResponseTime: 10000
  - name: Status
    url: https://status.iddqd.uk
    maxResponseTime: 5000

status-website:
  cname: status.iddqd.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night # light, dark, night or ocean
  metaTags:
    - name: "robots"
      content: "noindex"
  css: "footer p { display: none }"
  name: Status
  navbar:
    - title: Status
      href: /
    - title: Index
      href: https://iddqd.uk
  robotsText: "User-agent: *\nDisallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
