# Change these first
owner: iddqd-uk # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees: [tarampampam] # To be assigned to every downtime issue

sites:
  - name: Index page
    url: https://iddqd.uk
    maxResponseTime: 5000
  - name: Holy shit blog
    url: https://blog.iddqd.uk
    maxResponseTime: 5000
  - name: Status
    url: https://status.iddqd.uk
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.iddqd.uk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: night # light, dark, night or ocean
  metaTags:
    - name: "robots"
      content: "noindex"
  css: "footer p { display: none }"
  name: Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: *\nDisallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
